# Generated by Django 3.1.1 on 2020-10-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201027_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
